app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name='main'


urlpatterns = [
    path('', views.main, name='index'),
]

users/urls.py
from django.urls import path

from users import views

app_name='user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('basket/', views.basket, name='basket'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": True,
                                      "class": 'input-box',
                                      "placeholder": 'Имя пользователя',
                                     })
    )
    password = forms.CharField(\
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                          "class": 'input-box',
                                          "placeholder": 'Пароль',
                                         }),
    )

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrarionForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )
    
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from orders.models import Order
from users.forms import ProfileForm, UserLoginForm, UserRegistrarionForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы успешно вошли в аккаунт")
                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    
    context = {
        'form': form
    }

    return render(request, 'users/vhod.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrarionForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}, Вы успешно зарегистрировались")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrarionForm()
    
    context = {
        'form': form
    }

    return render(request, 'users/registration.html', context)

@login_required
def basket(request):
    
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f"{request.user.username}, Вы успешно изменили данные")
            return HttpResponseRedirect(reverse('user:basket'))
    else:
        form = ProfileForm(instance=request.user)
    
    order = Order.objects.filter(user=request.user)
    
    context = {
        'form': form,
        'orders': order
    }

    return render(request, 'users/korzina.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы успешно вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel='stylesheet' href='{% static 'css/stylevhod.css' %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tinos:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Авторизация/Вход</title>

</head>

<body>

    <div class="wrapper">
        <form action="{% url 'user:registration' %}" method="post">
            {% csrf_token %}
            <a href="{% url "main:index" %}">&larr;</a>
            <h1>Регистрация</h1>

            <div class="input-box">
                <input type="text" placeholder="Ваше имя" id="id_first_name" name="first_name" 
                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required>
                {% if form.first_name.errors %} {{ form.first_name.errors }} {% endif %}
            </div>
            
            <div class="input-box">
                <input type="text" placeholder="Ваше фамилия" id="id_last_name" name="last_name" 
                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required>
                {% if form.last_name.errors %} {{ form.last_name.errors }} {% endif %}
            </div>
            
            <div class="input-box">
                <input type="text" placeholder="Имя пользователя" id="id_username" name="username" 
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
                {% if form.username.errors %} {{ form.username.errors }} {% endif %}
            </div>

            <div class="input-box">
                <input type="text" placeholder="email" id="id_email" name="email"
                value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required>
                {% if form.email.errors %} {{ form.email.errors }} {% endif %}
            </div>

            <div class="input-box">
                <input type="password" placeholder="Введите пароль" id="id_password1" name="password1"
                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}" required>
                {% if form.password1.errors %} {{ form.password1.errors }} {% endif %}
            </div>

            <div class="input-box">
                <input type="password" placeholder="Повторите пароль" id="id_password2" name="password2"
                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}" required>
                {% if form.password2.errors %} {{ form.password2.errors }} {% endif %}
            </div>

            <button type="submit" class="btn">Зарегистрироваться</button>

            <div class="register-link">
                <p>Вы уже зарегистрированы? <a href="{% url 'user:login' %}">Авторизация</a></p>
            </div>

        </form>
    </div>

    <script src='{% static 'js/app.js' %}'></script>

</body>

</html>

users/templates/users/vhod.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel='stylesheet' href='{% static 'css/stylevhod.css' %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tinos:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Авторизация/Вход</title>

</head>

<body>

    <div class="wrapper">
        <form action="{% url 'user:login' %}" method="post">
            <a href="{% url "main:index" %}">&larr;</a>
            <h1>Вход</h1>
            {% csrf_token %}
            
            {% if request.GET.next %}
                <input type="hidden" name="next" value={{request.GET.next}}>
            {% endif %}
            
            <div class="input-box">
                {{ form.username }}
            </div>

            <div class="input-box">
                {{ form.password }}
            </div>

                {% comment %} вывод ошибки {% endcomment %}
                {% if form.non_field_errors %}
                <p>{{ form.non_field_errors }}</p>
                {% endif %}
                {% comment %}  {% endcomment %}
            <button type="submit" class="btn">Войти</button>
            <div class="register-link">
                <p>У вас нет учетной записи? <a href="{% url "user:registration" %}">Регистрация</a></p>
            </div>

        </form>
    </div>

    <script src='{% static 'js/app.js' %}'></script>

</body>

</html>