app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path

from basket import views

app_name='basket'

urlpatterns = [
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_change/', views.basket_change, name='basket_change'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

catalog/urls.py
from django.urls import path

from catalog import views

app_name='catalog'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

users/urls.py
from django.urls import path

from users import views

app_name='user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('basket/', views.basket, name='basket'),
    path('logout/', views.logout, name='logout'),
]

catalog/models.py
from django.db import models


class Suppliers(models.Model):

    name = models.CharField(max_length=100, unique=True, blank=False, null=False, verbose_name='Название')

    class Meta:
        db_table = 'supplier'
        verbose_name = 'Поставщика'
        verbose_name_plural = 'Поставщики'

    def __str__(self):
        return self.name


class Products(models.Model):

    name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    articul = models.CharField(max_length=100, blank=False, unique=True, null=False, verbose_name='Артикул')
    price = models.DecimalField(default=0.00, max_digits=8, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, verbose_name='Поставщик')

    class Meta:
        db_table = 'product'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ("id",)

    def __str__(self):
        return self.name

catalog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from .utils import q_search

from .models import Products


def catalog(request):

    page = request.GET.get('page', 1)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    products = Products.objects.all()

    if query:
        products = q_search(query)

    if order_by:
        products = products.order_by(order_by)

    paginator = Paginator(products, 3)
    current_page = paginator.page(int(page))

    context ={
        'products': current_page,
    }

    return render(request, 'catalog/index1.html', context)

def product(request, product_slug):
    
    products = Products.objects.get(slug=product_slug)
    
    context ={
        'products': products,
    }

    return render(request, 'catalog/tovar.html', context)

catalog/templates/catalog/index1.html
{% load static %}
{% load product_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel='stylesheet' href='{% static "css/style.css" %}'>
    <link rel='stylesheet' href='{% static "css/footer.css" %}'>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tinos:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Прайс</title>
</head>

<body>

<div class="container-body">
    
        <!--<div class='header'>-->
        <div class='poloska'>
            <div class='container'>
    
                <div class='header-line'>
                    <div class='header-logo'>
                        <img src="{% static "img/logogo.png" %}" alt="">
                    </div>
    
                    <div class='nav'>
                        <a class='nav-item' href="{% url "main:index" %}">ГЛАВНАЯ</a>
                        <a class='nav-item' href="{% url "catalog:index" %}">ПРАЙС</a>
                        <a class="nav-item" href="{% url "main:index" %}#cards">О НАС</a>
                        <a class="nav-item" href="{% url "main:index" %}#contact">КОНТАКТЫ</a>
                    </div>
    
                    <div class='cart'>
                        <a href="{% url 'user:basket' %}">
                            <img class='cart-img' src="{% static 'img/cart.png' %}" alt="">
                        </a>
                    </div>
    
                    <div class='phone'>
                        <div class='phone-holder'>
                            <div class='phone-img'>
                                <img src="{% static 'img/phone.png' %}" alt="">
                            </div>
    
                            <div class='number'><a class='num' href='#'>+999-888-76-54</a></div>
                        </div>
    
                        <div class='phone-text'>
    
                        </div>
                    </div>
    
                    <div class='profile-container-r'>
                        {% if not user.is_authenticated %}
                            <a href='{% url "user:login" %}'>АВТОРИЗАЦИЯ/ВХОД</a>
                        {% else %}
                            {% if user.is_superuser or user.is_staff %}
                                <a href="{% url 'admin:index' %}">Админ-панель</a> /
                            {% else %}
                                <a href="{% url 'user:basket' %}">{{ user.username }}</a> /    
                            {% endif %}
                            <a href="{% url 'user:logout' %}">Выйти</a>
                        {% endif %}
                    </div>
                </div>
    
            </div>
        </div>

        <!-- каталог -->
        <div class='container-catalog'>
            {% include "includes/notifications.html" %}
            <div class="search-sort">

                <form class="search-form" action="{% url "catalog:search" %}" method="get">
                    <input type="text" name="q" placeholder="Поиск...">
                    <button class="search-btn">Применить</button>
                </form>
                
                <form class="order-form" method="get" action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" %}{% endif %}">
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}
                    <select name="order_by">
                        <option value="price">Цена (по возрастанию)</option>
                        <option value="-price">Цена (по убыванию)</option>
                        <option value="name">Название (по алфавиту)</option>
                        <option value="-name">Название (в обратном порядке)</option>
                    </select>
                    <button class="search-btn">Применить</button>
                </form>

            </div>
    
            <div class="container-price">
                {% if request.GET.q is not empty%}
                    <div class="search-result">
                    {% comment %} <link rel="stylesheet" href="{% static 'css/my_footer.css' %}" /> {% endcomment %}
                    <h3>По результатам поиска "{{ request.GET.q }}" было найдено следующее:</h3>

                    {% if not products %}
                        <br><h3>По запросу "{{ request.GET.q }}" ничего не было найдено.</h3>
                    {% endif %}
                    </div>
                {% endif %}
                {% comment %} вывод карт {% endcomment %}
                {% for product in products %}
                    <div class="card1">
    
                        <img src="{{ product.image.url }}" alt="" onclick="window.location.href = '{% url "catalog:product" product.slug %}';" onmouseover="this.style.cursor='pointer';">

                        <p onclick="window.location.href = '{% url "catalog:product" product.slug %}';" onmouseover="this.style.cursor='pointer';">
                            {{ product.name }}<br> арт.{{ product.articul }}
                        </p>

                        <div class="description" onclick="window.location.href = '{% url "catalog:product" product.slug %}';" onmouseover="this.style.cursor='pointer';">

                            <p>Цена: {{ product.price }}</p>

                        </div>

                        
                        <a href="{% url "basket:basket_add" %}" class="add-to-cart"
                        data-product-id="{{ product.id }}">
                            {% csrf_token %}
                            <button>В корзину</button>
                        </a>
                    </div>
                {% endfor %}
                {% comment %} конец вывода карт {% endcomment %}
                
                {% if products %}
                <div class="container-pagination">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">

                          <div>
                              <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                                <a class="page-link" href="{% if products.has_previous %}?{% change_params page=products.previous_page_number %}{% else %}#
                                {% endif %}" aria-label="Previous">
                                  <span aria-hidden="true">&laquo;</span>
                                </a>
                              </li>
                          </div>
                        
                          {% for page in products.paginator.page_range %}
                            {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                                <li class="page-item {% if page == products.number %}active{% endif %}">
                                    <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                                </li>
                            {% endif %}
                          {% endfor %}

                          <div>
                              <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                                <a class="page-link" href="{% if products.has_next %}?{% change_params page=products.next_page_number %}{% else %}#
                                {% endif %}" aria-label="Next">
                                  <span aria-hidden="true">&raquo;</span>
                                </a>
                              </li>
                          </div>

                        </ul>
                      </nav>
                </div>
                {% endif %}
            </div>
    
        </div>

        <div class='footer'>
            Copyright 2022
            </div>
</div>

<script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
<script src="{% static "js/jquery-ajax.js" %}"></script>
<script src='{% static 'js/app.js' %}'></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script>
    function closeNotification(button) {
        const notification = button.parentElement;
        setTimeout(() => {
            notification.style.display = "none";
        }, 500); 
    }

    // Автоматическое  закрытие  через  7  секунд
    setTimeout(() => {
        const notifications = document.querySelectorAll('.notification');
        notifications.forEach(notification => {
            notification.style.opacity = 0;
            setTimeout(() => {
                notification.remove();
            }, 500);
        });
    }, 3000);
</script>

</body>

</html>

catalog/templates/catalog/tovar.html
{% load static %}
{% load product_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel='stylesheet' href='{% static "css/style.css" %}'>
    <link rel='stylesheet' href='{% static "css/footer.css" %}'>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tinos:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ products.name }}</title>
</head>

<body>

<div class="container-body">
    
        <!--<div class='header'>-->
        <div class='poloska'>
            <div class='container'>
    
                <div class='header-line'>
                    <div class='header-logo'>
                        <img src="{% static "img/logogo.png" %}" alt="">
                    </div>
    
                    <div class='nav'>
                        <a class='nav-item' href="{% url "main:index" %}">ГЛАВНАЯ</a>
                        <a class='nav-item' href="{% url "catalog:index" %}">ПРАЙС</a>
                        <a class="nav-item" href="{% url "main:index" %}#cards">О НАС</a>
                        <a class="nav-item" href="{% url "main:index" %}#contact">КОНТАКТЫ</a>
                    </div>
    
                    <div class='cart'>
                        <a href="{% url 'user:basket' %}">
                            <img class='cart-img' src="{% static 'img/cart.png' %}" alt="">
                        </a>
                    </div>
    
                    <div class='phone'>
                        <div class='phone-holder'>
                            <div class='phone-img'>
                                <img src="{% static 'img/phone.png' %}" alt="">
                            </div>
    
                            <div class='number'><a class='num' href='#'>+999-888-76-54</a></div>
                        </div>
    
                        <div class='phone-text'>
    
                        </div>
                    </div>
    
                    <div class='profile-container-r'>
                        {% if not user.is_authenticated %}
                            <a href='{% url "user:login" %}'>АВТОРИЗАЦИЯ/ВХОД</a>
                        {% else %}
                            {% if user.is_superuser or user.is_staff %}
                                <a href="{% url 'admin:index' %}">Админ-панель</a> /
                            {% else %}
                                <a href="{% url 'user:basket' %}">{{ user.username }}</a> /    
                            {% endif %}
                            <a href="{% url 'user:logout' %}">Выйти</a>
                        {% endif %}
                    </div>
                </div>
    
            </div>
        </div>

        {% include "includes/notifications.html" %}
        <div class="container-product">
        <a href="{% url 'catalog:index' %}">&larr; Каталог</a>
            <div>
                <div>
                    <img src="{{ products.image.url }}">
                    <p class="product-name">{{ products.name }}</p>
                </div>
                <div class="description-product">
                    <a href="{% url "basket:basket_add" %}" class="add-to-cart"
                    data-product-id="{{ products.id }}">
                        {% csrf_token %}
                        <button>В корзину</button>
                    </a>
                    <div>
                        <p>Цена: {{ products.price }}</p>
                        <p>Артикул: {{ products.articul }}</p>
                        <p>Поставщик: {{ products.supplier.name }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class='footer'>
            Copyright 2022
            </div>
</div>

<script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
<script src="{% static "js/jquery-ajax.js" %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script>
    function closeNotification(button) {
        const notification = button.parentElement;
        setTimeout(() => {
            notification.style.display = "none";
        }, 500); 
    }

    // Автоматическое  закрытие  через  7  секунд
    setTimeout(() => {
        const notifications = document.querySelectorAll('.notification');
        notifications.forEach(notification => {
            notification.style.opacity = 0;
            setTimeout(() => {
                notification.remove();
            }, 500);
        });
    }, 3000);

</script>
</body>

</html>